### ISSUE TITLE
Esclarecimento sobre o local da ajuda

### ISSUE THREAD

**Issue by ingridmachado** [brendaw/yt-mp3#1]
Oi, @brendaw. No segundo item TO-DO tem o seguinte texto:

- Add a menu and more help information on the script

A informação de ajuda deve ser exibida quando o usuário rodar o script ou seria adicionar mais texto no README?

**Comment by brendaw** [comment]
Olá, @ingridmachado. Essa tarefa é para mostrar a informação de ajuda quando for rodado o script pelo usuário. Sendo quando for passado o argumento `--help` ou quando executando o script sem argumentos.

Imaginei o conteúdo de ajuda mais ou menos assim:

```bash
$ yt-mp3
Usage: yt-mp3 [OPTION]... [FILE]...
Download a list of MP3 musics from YouTube at command-line.
...
```

Sinta-se livre para sugerir qualquer adição ou alteração nessa proposta.
